version: "3.9"
services:
  db:
    container_name: db_app
    image: postgres:15.2
    env_file:
      - .env-non-dev
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-non-dev
    container_name: arduino_app
    ports:
      - "9999:8000"
    restart: on-failure
    depends_on:
      - db
